language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install coveralls pytest-cov pytest plateo
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov bandwitch --cov-report term-missing

after_success:
  - coveralls
